### ISSUE TITLE
Focus styles

### ISSUE THREAD

**Issue by ngscheurich** [adamculpepper/toggle-switchy#12]
I'd love to see some aesthetically consistent custom focus styles on these bad boys. Great work!

**Comment by adamculpepper** [comment]
Thanks for the suggestion @ngscheurich! This has been worked into the styles. For color, I felt like something close to what most browsers use for color was appropriate and I used a `box-shadow` instead of the `outline` default most browsers use by default so the style isn't so harsh.

Check it out and let me know what you think!

*Tested in Chrome, Firefox, IE10 and Edge.
